import type { SelectItem } from '../types';

// US states and territories (from legacy client)
export const STATE_TERRITORY_OPTIONS: SelectItem[] = [
  { value: '', label: '--Select an option--' },
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AS', label: 'American Samoa' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'DC', label: 'District of Columbia' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'GU', label: 'Guam' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MP', label: 'Northern Mariana Islands' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'VI', label: 'Virgin Islands' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' }
];

// Industry/Business options (from legacy client)
export const INDUSTRY_OPTIONS: SelectItem[] = [
  { value: '', label: '--Select an option--' },
  { value: 'ACO', label: 'ACO' },
  { value: 'CHC/FQHC', label: 'CHC/FQHC' },
  { value: 'Clinic', label: 'Clinic' },
  { value: 'HIE', label: 'HIE' },
  { value: 'HIT Consulting', label: 'HIT Consulting' },
  { value: 'HIT Software', label: 'HIT Software' },
  { value: 'Hospital', label: 'Hospital' },
  { value: 'Lab', label: 'Lab' },
  { value: 'Network', label: 'Network' },
  { value: 'Other', label: 'Other' },
  { value: 'Payer', label: 'Payer' },
  { value: 'Physicians Group', label: 'Physicians Group' },
  { value: 'Private Practice', label: 'Private Practice' },
  { value: 'Public Health Agency', label: 'Public Health Agency' },
  { value: 'Radiology Center', label: 'Radiology Center' },
  { value: 'University', label: 'University' }
];

// Role options (from legacy client)
export const ROLE_OPTIONS: SelectItem[] = [
  { value: '', label: '--Select an option--' },
  { value: 'C-Suite', label: 'C-Suite' },
  { value: 'Consultant - Advisor', label: 'Consultant - Advisor' },
  { value: 'Consultant - Engineer', label: 'Consultant - Engineer' },
  { value: 'Consultant - Implementer', label: 'Consultant - Implementer' },
  { value: 'Employee - Engineer', label: 'Employee - Engineer' },
  { value: 'Employee - Manager', label: 'Employee - Manager' },
  { value: 'Employee - Director', label: 'Employee - Director' },
  { value: 'Employee - VP', label: 'Employee - VP' },
  { value: 'Independent Contractor', label: 'Independent Contractor' },
  { value: 'Other', label: 'Other' }
];

// Country options (ISO country list, sorted)
export const COUNTRY_OPTIONS: SelectItem[] = [
  { value: '', label: '--Select an option--' },
  { value: 'US', label: 'United States' },
  { value: 'CA', label: 'Canada' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'AU', label: 'Australia' },
  { value: 'DE', label: 'Germany' },
  { value: 'FR', label: 'France' },
  { value: 'IN', label: 'India' },
  { value: 'JP', label: 'Japan' },
  { value: 'CN', label: 'China' },
  { value: 'BR', label: 'Brazil' },
  { value: 'MX', label: 'Mexico' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'RU', label: 'Russia' },
  { value: 'IT', label: 'Italy' },
  { value: 'ES', label: 'Spain' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'SE', label: 'Sweden' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'SG', label: 'Singapore' },
  // ... (add more as needed)
]; 